// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxqunhauabqjcklhkrsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cXVuaGF1YWJxamNrbGhrcnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTc4NzksImV4cCI6MjA1NjQ5Mzg3OX0.MPCpFPBzRnyFGVsO6CqpeuV7JT6usSdEhy4kLa9Vt_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);